name: tunai
description: AI-based DSP speaker tuning platform

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  just_audio: ^0.9.36
  audio_session: ^0.1.25
  fftea: ^1.5.0+1
  flutter_blue_plus: ^1.31.15
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.68.0
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.8
  dio: ^5.9.2
  flutter_sound: ^9.2.13
  shared_preferences: ^2.5.3
  device_info_plus: ^12.4.0
  crypto: ^3.0.7
  flutter_web_auth_2: ^5.0.3
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  google_generative_ai: ^0.4.7
  mobile_scanner: ^7.2.0
  http: ^1.2.0
  flutter_native_splash: ^2.4.6
  cloud_functions: ^4.7.6
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_background: "#000000"
  min_sdk_android: 21
  macos:
    generate: true
    image_path: "assets/images/icon.png"
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_icon.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/splash_icon.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash_icon.png
  fullscreen: true
