import 'package:flutter/foundation.dart';

import 'correction_plan.dart';
import 'personal_optimization_context.dart';

/// A fully deterministic, consumer-language explanation of WHY a Tune sounds
/// the way it does — the "Explainable Sound Experience".
///
/// Every message is generated by rules from real, stored perceptual context
/// (see [SoundExplanationGenerator]); NO AI call is involved, so the same Tune
/// always explains itself the same way, offline, instantly. Contains only
/// plain language — never Hz, dB, Q, PEQ, filter, or any DSP term. A message
/// is null when there is nothing real to say for it, and the UI shows only the
/// non-null ones.
@immutable
class SoundExplanation {
  /// What was preserved from the speaker's factory voicing.
  final String? factoryMessage;

  /// What the room did and how it was corrected.
  final String? roomMessage;

  /// How the user's stated preference was reflected.
  final String? preferenceMessage;

  /// One-line summary tying it together.
  final String? overallMessage;

  const SoundExplanation({
    this.factoryMessage,
    this.roomMessage,
    this.preferenceMessage,
    this.overallMessage,
  });

  bool get hasContent =>
      _nonEmpty(factoryMessage) ||
      _nonEmpty(roomMessage) ||
      _nonEmpty(preferenceMessage) ||
      _nonEmpty(overallMessage);

  static bool _nonEmpty(String? s) => s != null && s.trim().isNotEmpty;
}

/// Rules-only generator: [PersonalOptimizationContext] (+ optional
/// [CorrectionPlan]) → [SoundExplanation]. Deterministic by design — the
/// explanation must never depend on a network call or a model's mood.
class SoundExplanationGenerator {
  const SoundExplanationGenerator();

  SoundExplanation generate(
    PersonalOptimizationContext context, {
    CorrectionPlan? plan,
    bool ko = true,
  }) {
    return SoundExplanation(
      factoryMessage: _factory(context, ko),
      roomMessage: _room(context, plan, ko),
      preferenceMessage: _preference(context, plan, ko),
      overallMessage: _overall(context, plan, ko),
    );
  }

  String? _factory(PersonalOptimizationContext c, bool ko) {
    final f = c.factoryReference;
    if (f == null) return null;
    // Describe the factory voicing character in plain language.
    final character = switch (f.targetCharacter) {
      'natural_balanced' => ko ? '자연스러운 밸런스' : 'a natural, balanced sound',
      'warm' => ko ? '따뜻한 음색' : 'a warm character',
      'reference' => ko ? '레퍼런스 사운드' : 'a reference sound',
      _ => ko ? '기본 음색' : 'its core character',
    };
    return ko
        ? '${f.speakerModel}이(가) 출하 시 의도한 $character을(를) 그대로 유지했습니다.'
        : 'Kept ${f.speakerModel}’s intended $character intact.';
  }

  String? _room(
      PersonalOptimizationContext c, CorrectionPlan? plan, bool ko) {
    // Judgment layer: an unreliable measurement is NOT aggressively corrected.
    // Say honestly that the factory sound was held rather than implying a fix.
    if (c.confidence == 'low' ||
        plan?.strategy == CorrectionStrategy.lowConfidenceIgnore) {
      return ko
          ? '측정이 다소 불안정하여, 무리한 조정 없이 출하 시 음색을 그대로 유지했습니다.'
          : 'The measurement was a little unsettled, so we held the speaker’s '
              'original sound rather than over-correcting.';
    }
    // No room problem → nothing was corrected; say so honestly rather than
    // implying a fix that did not happen.
    if (c.roomCondition == 'balanced') {
      return ko
          ? '이 공간은 이미 균형이 좋아 큰 조정이 필요하지 않았습니다.'
          : 'Your space was already well balanced, so little needed changing.';
    }
    final where = _placementPhrase(c, ko);
    final problem = switch (c.roomCondition) {
      'bassBoom' => ko ? '저역 울림' : 'a low-end boom',
      'boxyMidrange' => ko ? '중음의 울림' : 'a boxy midrange',
      'harshTreble' => ko ? '고음의 날카로움' : 'a harsh treble',
      _ => ko ? '공간의 불균형' : 'a room imbalance',
    };
    final action = switch (plan?.strategy) {
      CorrectionStrategy.fillRoomDip =>
        ko ? '부족했던 부분을 채웠습니다' : 'filled what the room was missing',
      _ => ko ? '정리했습니다' : 'was calmed',
    };
    return ko
        ? '$where$problem을(를) $action.'
        : 'We $action $problem$where.';
  }

  String? _preference(
      PersonalOptimizationContext c, CorrectionPlan? plan, bool ko) {
    // Was the preference actually APPLIED to the tuning, or held as secondary?
    // On a less-than-trustworthy measurement the judgment layer protects the
    // factory sound and keeps the preference secondary — say "참고했습니다"
    // (considered), never "반영했습니다" (applied).
    final applied = c.confidence == 'stable' &&
        plan?.strategy != CorrectionStrategy.protectFactoryCharacter &&
        plan?.strategy != CorrectionStrategy.lowConfidenceIgnore;
    String verb() => ko
        ? (applied ? '반영했습니다' : '참고했습니다')
        : (applied ? 'Reflected' : 'Kept in mind');
    String pref(String koWord, String enWord) => ko
        ? '$koWord 취향을 ${verb()}.'
        : '${verb()} your $enWord preference.';

    switch (c.userPreference) {
      case 'warm':
        return pref('따뜻한', 'warmer');
      case 'detailed':
        return pref('또렷한', 'detail-focused');
      case 'relaxed':
        return pref('편안한', 'relaxed');
      case 'vocal':
        return pref('보컬 중심', 'vocal-forward');
      case 'natural':
      case null:
        break; // Natural / none = no override to announce.
    }
    // CONTEXT-ONLY — a listening goal like "long listening" has no safe
    // existing preference mapping, so it did NOT change the DSP. It is
    // honestly described as CONSIDERED ("참고했습니다" / "kept in mind"), never
    // as applied — this is the PART 6/7 reflected-vs-context distinction.
    final goal = c.listeningIntent['listeningGoal'];
    if (goal == 'longListening') {
      return ko
          ? '오래 들어도 편안한 청취를 참고했습니다.'
          : 'Kept comfortable long listening in mind.';
    }
    if (goal == 'movie') {
      return ko ? '영화 감상 환경을 참고했습니다.' : 'Kept movie listening in mind.';
    }
    return null;
  }

  String? _overall(
      PersonalOptimizationContext c, CorrectionPlan? plan, bool ko) {
    if (c.roomCondition == 'balanced' && !c.hasUserSignal) {
      return ko
          ? '출하 시의 소리를 이 공간에 맞게 그대로 살렸습니다.'
          : 'Preserved the speaker’s original sound for your space.';
    }
    return ko
        ? '출하 시 의도한 소리를 지키면서, 이 공간과 취향에 맞게 다듬었습니다.'
        : 'Kept the speaker’s intended sound while adapting it to your space and taste.';
  }

  String _placementPhrase(PersonalOptimizationContext c, bool ko) {
    // Placement is only spelled out when it is actually present in the context;
    // never guessed. Absent → a neutral "in your space" phrasing.
    final placement = c.listeningIntent['placement'];
    return switch (placement) {
      'desk' => ko ? '책상 환경에서 생긴 ' : '',
      'near_wall' => ko ? '벽 근처에서 생긴 ' : '',
      _ => ko ? '공간에서 나타난 ' : '',
    };
  }
}
